import { StyleSheet } from "react-native";
import colors from "@/theme";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.dark.background,
  },
  header: {
    backgroundColor: colors.dark.header,
    paddingTop: 60,
    paddingBottom: 20,
    width: "100%",
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
    paddingHorizontal: 20,
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 5,
  },
  headerTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 15,
  },
  headerTitle: {
    color: colors.dark.text,
    fontSize: 28,
    fontWeight: "800",
  },
  content: {
    flex: 1,
    width: "100%",
  },
  contactCard: {
    flexDirection: "row",
    alignItems: "center",
    padding: 14,
    marginHorizontal: 16,
    marginVertical: 8,
    backgroundColor: colors.dark.card,
    borderRadius: 20,
    gap: 14,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.03)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  avatar: {
    width: 55,
    height: 55,
    borderRadius: 16,
  },
  contactInfo: {
    flex: 1,
  },
  contactName: {
    color: colors.dark.text,
    fontSize: 17,
    fontWeight: "600",
    marginBottom: 2,
  },
  contactPhone: {
    color: colors.dark.textSecondary,
    fontSize: 14,
  },
  fab: {
    position: "absolute",
    bottom: 30,
    right: 20,
    backgroundColor: colors.dark.primary,
    width: 65,
    height: 65,
    borderRadius: 32.5,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: colors.dark.primary,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.4,
    shadowRadius: 12,
    elevation: 8,
  },
  sheetContent: {
    padding: 24,
    backgroundColor: colors.dark.background,
    gap: 20,
  },
  sheetHeader: {
    alignItems: "center",
    marginBottom: 10,
    gap: 10,
  },
  sheetAvatar: {
    width: 90,
    height: 90,
    borderRadius: 45,
    marginBottom: 10,
    borderWidth: 2,
    borderColor: "rgba(255,255,255,0.1)",
  },
  sheetTitle: {
    color: colors.dark.text,
    fontSize: 24,
    fontWeight: "800",
  },
  sheetPhone: {
    color: colors.dark.textSecondary,
    fontSize: 17,
    fontWeight: "400",
  },
  sheetMenu: {
    gap: 14,
  },
  menuItem: {
    flexDirection: "row",
    alignItems: "center",
    padding: 18,
    backgroundColor: colors.dark.card,
    borderRadius: 16,
    gap: 14,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.03)",
  },
  menuItemText: {
    color: colors.dark.text,
    fontSize: 16,
    fontWeight: "600",
  },
  callButton: {
    backgroundColor: "#34C759",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    padding: 18,
    borderRadius: 18,
    gap: 10,
    marginTop: 10,
    shadowColor: "#34C759",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  callButtonText: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "700",
  },
});

export default styles;
